### ISSUE TITLE
rotpole projection to ESRI shape file

### ISSUE THREAD

**Issue by guziy** [matplotlib/basemap#306]
Hi:

Does anyone know how to convert rotpole projection to ESRI format, to write data into a shape file?

I tried to do it using basemap.proj4string, and then pycrs or gdal, but there are some things missing from the proj4string...

I've added +ellps, but +o_proj=longlat +proj=ob_tran do not seem to be recognized...

Here is the proj4 I am trying to use:

+R=6370997.0 +lon_0=-97.0 +o_lat_p=42.5 +units=m +proj=ob_tran +o_lon_p=180.0 +o_proj=longlat  +ellps=WGS84

pycrs complains that it does not know the specified name:

```
Traceback (most recent call last):
  File "/Users/huziy/skynet2/RESCUE/skynet3_rech1/huziy/Netbeans Projects/Python/RPN/src/crcm5/mh_domains/show_domain_with_drainage_area.py", line 213, in <module>
    main()
  File "/Users/huziy/skynet2/RESCUE/skynet3_rech1/huziy/Netbeans Projects/Python/RPN/src/application_properties.py", line 15, in wrapper
    func(*args, **kwargs)
  File "/Users/huziy/skynet2/RESCUE/skynet3_rech1/huziy/Netbeans Projects/Python/RPN/src/crcm5/mh_domains/show_domain_with_drainage_area.py", line 203, in main
    crs = pycrs.parser.from_proj4(bmp.proj4string + " +ellps={}".format("WGS84"))
  File "/Users/huziy/virtualenvs/py3.4/lib/python3.4/site-packages/pycrs/parser.py", line 565, in from_proj4
    raise Exception("The specified projection name could not be found")
Exception: The specified projection name could not be found
```

Below is my test code (the pj=basemap.proj4string + " +ellps=WGS84"):

```python
    import pycrs
    pj = "+R=6370997.0 +lon_0=-97.0 +o_lat_p=42.5 +units=m +proj=ob_tran +o_lon_p=180.0 +o_proj=longlat  +ellps=WGS84
"
    crs = pycrs.parser.from_proj4(pj)
    print(crs.to_esri_wkt())
```

Cheers

**Comment by micahcochran** [comment]
@guziy  I tried to do the same conversion with GDAL/OGR, which does **NOT** work:
```Python
from osgeo import osr

srs = osr.SpatialReference()
proj4_text = "+R=6370997.0 +lon_0=-97.0 +o_lat_p=42.5 +units=m +proj=ob_tran +o_lon_p=180.0 +o_proj=longlat  +ellps=WGS84"

srs.ImportFromProj4(proj4_text) # returns 5 which is an OGRERR_CORRUPT_DATA

srs.MorphToESRI() # converts the WKT to an ESRI-compatible format
print("ESRI compatible WKT for use as .prj:" % srs.ExportToWkt())
```

PyCRS by its own admission is beta software.  Even the [libproj.pdf](https://github.com/OSGeo/proj.4/blob/master/docs/old/libproj.pdf) leaves the `+proj=ob_tran` a little under documented with its question marks.
