### ISSUE TITLE
Anaconda/windows + 3.6 + basemap issue

### ISSUE THREAD

**Issue by cmaurer7** [matplotlib/basemap#345]
I know this is not necessarily supported but I just updated to the newest Anaconda version : 4.3.14 with python 3.6 and I also installed the latest version of Visual Studio on Windows 10 OS. I installed 
basemap‑1.1.0‑cp36‑cp36m‑win_amd64.whl 
from http://www.lfd.uci.edu/~gohlke/pythonlibs/ 
and it does not work. . Any help would be appreciated. Here is the error I'm getting:

C:\>pip install C:\Users\cmaur\Downloads\basemap-1.1.0-cp36-cp36m-win_amd64.whl
Processing c:\users\cmaur\downloads\basemap-1.1.0-cp36-cp36m-win_amd64.whl
Collecting pyshp>=1.2.0 (from basemap==1.1.0)
  Using cached pyshp-1.2.10.tar.gz
Collecting pyproj>=1.9.3 (from basemap==1.1.0)
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\msvc.py", line 474, in __init__
    IndexError: list index out of range

   During handling of the above exception, another exception occurred:

   Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\cmaur\AppData\Local\Temp\pip-build-ghvsa3dq\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "C:\Anaconda3\lib\distutils\_msvccompiler.py", line 304, in compile
        self.initialize()
      File "C:\Anaconda3\lib\distutils\_msvccompiler.py", line 197, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\msvc.py", line 170, in msvc14_get_vc_env
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\msvc.py", line 767, in __init__
      File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\msvc.py", line 477, in __init__
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by WeatherGod** [comment]
I am not a windows expert, but I think you need to match the version of
Visual Studio to the version used to build the python distribution (as
opposed to simply "the latest version"). The error message says that you
need version 14.0.

**Comment by cgohlke** [comment]
Basemap now depends on pyproj, Try `conda install -c conda-forge pyproj=1.9.5.1` or use the wheels from <http://www.lfd.uci.edu/%7Egohlke/pythonlibs/#pyproj>, then install basemap again.

**Comment by cmaurer7** [comment]
The package from http://www.lfd.uci.edu/~gohlke/pythonlibs/ 
worked once I installed the 2015 Visual C++ Build Tools from 
http://landinghub.visualstudio.com/visual-cpp-build-tools 

Download the package and use:
pip install putYourPathHere\basemap-1.1.0-cp36-cp36m-win_amd64.whl

My mistake was thinking installing Visual Studio 2017 would solve the problem. 
Thank you for your help.

**Comment by WeatherGod** [comment]
Glad you got that sorted out!
