### ISSUE TITLE
python simpletest.py doesn't work in python 3.6.1

### ISSUE THREAD

**Issue by richiverse** [matplotlib/basemap#358]
steps to repro:
```bash
python simpletest.py 
/home/rich/repos/geo/venv/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3608: MatplotlibDeprecationWarning: The ishold function was de
precated in version 2.0.
  b = ax.ishold()
/home/rich/repos/geo/venv/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:3675: MatplotlibDeprecationWarning: axes.hold is deprecated.
    See the API Changes document (http://matplotlib.org/api/api_changes.html)
    for more details.
  ax.hold(b)
Traceback (most recent call last):
  File "simpletest.py", line 12, in <module>
    cs = m.contourf(x,y,etopo,30,cmap=plt.cm.jet)
  File "/home/rich/repos/geo/venv/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 521, in with_transform
    return plotfunc(self,x,y,data,*args,**kwargs)
  File "/home/rich/repos/geo/venv/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 3644, in contourf
    xx = x[x.shape[0]/2,:]
```

The problem is that *x.shape[0]/2* resolves to _270.0_ and an index slice must be an integer. PR on the way.

**Comment by richiverse** [comment]
nvm I htink this was fixed in the mpl_toolkit repo. going to switch to cartopy in the meantime. A lot of the run_all.py tests failed for float errors in py3.6

**Comment by guziy** [comment]
Works for me on py3.4... Which version of basemap you are using, try updating?
