### ISSUE TITLE
tag 1.1.1 please (because of import mpl_toolkits.basemap as basemap fails on matplotlib)

### ISSUE THREAD

**Issue by ReimarBauer** [matplotlib/basemap#424]
Hi there

as this issue is already fixed, please tag 1.1.1 so that we can make a new build on conda-forge.

I found this by CicleCI trying to build our tool

**installed packages**
```
  basemap:              1.1.0-py35h50ae964_6                 conda-forge
  matplotlib:           3.0.0-py35h0b34cb6_1                 conda-forge
```
**Problem**

from matplotlib.cbook import is_scalar, dedent
ImportError: cannot import name 'is_scalar'

Looks like is_scalar was moved or renamed

```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/mss", line 7, in <module>
    from mslib.msui.mss_pyui import main
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/mss_pyui.py", line 49, in <module>
    from mslib.msui.mss_qt import ui_mainwindow as ui
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/mss_qt.py", line 157, in <module>
    globals()[mod] = importlib.import_module("mslib.msui.qt5." + mod)
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/qt5/ui_sideview_window.py", line 64, in <module>
    from mslib.msui.mpl_qtwidget import MplSideViewWidget
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/mpl_qtwidget.py", line 54, in <module>
    from mslib.msui import mpl_map
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mslib/msui/mpl_map.py", line 48, in <module>
    import mpl_toolkits.basemap as basemap
  File "/home/conda/feedstock_root/build_artifacts/mss_1537858909004/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 17, in <module>
    from matplotlib.cbook import is_scalar, dedent
ImportError: cannot import name 'is_scalar'
Tests failed for mss-1.7.3-py35_2.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for mss-1.7.3-py35_2.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: mss-1.7.3-py35_2.tar.bz2
Exited with code 1

```

**Comment by efiring** [comment]
v1.2.0rel tagged by @WeatherGod

**Comment by BerndtSam** [comment]
ETA on replacing the depreciated methods? Work around for time being?

**Comment by WeatherGod** [comment]
Install basemap from conda-forge. It has release v1.2.0 available, which has this fix.

**Comment by BerndtSam** [comment]
@WeatherGod - Thanks!

**Comment by IoannisNasios** [comment]
you can now install basemap from git. Release v1.2.0 is available

pip install -U git+https://github.com/matplotlib/basemap.git
