### ISSUE TITLE
 ImportError: dlopen ... symbol not found in flat namespace '_GEOSArea' 

### ISSUE THREAD

**Issue by bongotai** [matplotlib/basemap#524]
Hello! While using Peter Kuma's [ccplot](https://github.com/peterkuma/ccplot) I came accross this error:

`Traceback (most recent call last): File "/Users/joaquinx/opt/anaconda3/bin/ccplot", line 54, in <module> from mpl_toolkits import basemap File "/Users/joaquinx/opt/anaconda3/lib/python3.8/site-packages/mpl_toolkits/basemap/__init__.py", line 53, in <module> from mpl_toolkits.basemap import _geoslib ImportError: dlopen(/Users/joaquinx/opt/anaconda3/lib/python3.8/site-packages/mpl_toolkits/basemap/_geoslib.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_GEOSArea'`

Peter "re-cythonized" a version of the basemap respository and I tried one of basemap's samples on a Jupyter notebook finding the same error message again. I am running this on a Mac with the M1 chip though it seems it shouldn't be a problem since the OS translates the code via Rosetta.

`ImportError                               Traceback (most recent call last)
<ipython-input-1-5803946b5b59> in <module>
----> 1 from mpl_toolkits.basemap import Basemap
      2 import matplotlib.pyplot as plt
      3 import numpy as np
      4 # set up orthographic map projection with
      5 # perspective of satellite looking down at 50N, 100W.
` 
`~/opt/anaconda3/lib/python3.8/site-packages/mpl_toolkits/basemap/__init__.py in <module>
     51 import numpy as np
     52 import numpy.ma as ma
---> 53 from mpl_toolkits.basemap import _geoslib
     54 import functools
     55 
`
`ImportError: dlopen(/Users/joaquinx/opt/anaconda3/lib/python3.8/site-packages/mpl_toolkits/basemap/_geoslib.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_GEOSArea'`

Any clues on why this might be happening? thank you!

**Comment by bongotai** [comment]
The issue seems to be related to Apple M1 processor, as I tried runnig a basemap example on an Intel Mac and it worked perfectly.
