### ISSUE TITLE
Python 3.13 compatibility

### ISSUE THREAD

**Issue by jameswilburlewis** [matplotlib/basemap#608]
basemap does not "pip install" cleanly under Python 3.13.   Might be related to some of the pinned upper versions of package dependencies?  This environment had numpy 1.26.4 installed (so not a numpy 2.0 issue).

```
(pycharm_py313) jwl@jwl-new-mac pyspedas_py313 % pip install basemap       
Collecting basemap
  Using cached basemap-1.3.9.zip (156 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      Ignoring numpy: markers 'python_version == "3.10"' don't match your environment
      Ignoring numpy: markers 'sys_platform == "darwin" and (python_version >= "3.7" and python_version <= "3.9")' don't match your environment
      Ignoring numpy: markers 'sys_platform != "darwin" and (python_version >= "3.7" and python_version <= "3.9")' don't match your environment
      Ignoring numpy: markers 'python_version == "2.7" or (python_version >= "3.4" and python_version <= "3.6")' don't match your environment
      Ignoring numpy: markers 'python_version == "2.6" or (python_version >= "3.2" and python_version <= "3.3")' don't match your environment
      Ignoring cython: markers 'python_version == "3.2"' don't match your environment
      Collecting setuptools
        Using cached setuptools-75.4.0-py3-none-any.whl.metadata (6.8 kB)
      Collecting wheel
        Using cached wheel-0.45.0-py3-none-any.whl.metadata (2.3 kB)
      Collecting numpy==1.23.3
        Using cached numpy-1.23.3.tar.gz (10.7 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [32 lines of output]
            Traceback (most recent call last):
              File "/Users/jwl/anaconda3/envs/pycharm_py313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
                ~~~~^^
              File "/Users/jwl/anaconda3/envs/pycharm_py313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Users/jwl/anaconda3/envs/pycharm_py313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
                backend = _build_backend()
              File "/Users/jwl/anaconda3/envs/pycharm_py313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
                obj = import_module(mod_path)
              File "/Users/jwl/anaconda3/envs/pycharm_py313/lib/python3.13/importlib/__init__.py", line 88, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
              File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
              File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
              File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
              File "/private/var/folders/_4/hbrtgs_j1qlgl2f3fwjw2_kc0000gn/T/pip-build-env-83asxxgw/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 16, in <module>
                import setuptools.version
              File "/private/var/folders/_4/hbrtgs_j1qlgl2f3fwjw2_kc0000gn/T/pip-build-env-83asxxgw/overlay/lib/python3.13/site-packages/setuptools/version.py", line 1, in <module>
                import pkg_resources
              File "/private/var/folders/_4/hbrtgs_j1qlgl2f3fwjw2_kc0000gn/T/pip-build-env-83asxxgw/overlay/lib/python3.13/site-packages/pkg_resources/__init__.py", line 2172, in <module>
                register_finder(pkgutil.ImpImporter, find_on_path)
                                ^^^^^^^^^^^^^^^^^^^
            AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
            [end of output]
 
```

**Comment by DWesl** [comment]
Failing in `import setuptools.version` is odd; does `pip install --no-build-isolation basemap` do the same thing?

**Comment by molinav** [comment]
Currently, Python 3.13 is still not supported by `basemap` (there is also a pin `<3.13` for Python in `setup.py`). I am aware that Python 3.13 was released last October, and I would like to add the support, but currently I am a bit overloaded at my job.

Hopefully in December I will get some time free (aka Christmas present releases).

**Comment by jameswilburlewis** [comment]
@molinav Thanks for checking, I hope I've been good enough this year to be deserving of a nice Christmas release!

**Comment by wreckdump** [comment]
Are we still having issue with python 3.13?

**Comment by cvanelteren** [comment]
The or will install it for 3.13, but we are fixing it on another or in a more profound way. It is still a bit yank right. Depending on your needs it is worth it or not.

**Comment by molinav** [comment]
@jameswilburlewis Support for Python 3.13 in `basemap` has been added in https://github.com/matplotlib/basemap/pull/619. However, from your traceback, I may assume that you are trying to install on MacOS, right? So far, the MacOS wheels on PyPI were built manually by myself in a personal Mac mini M1, but I would like to include the build workflows for MacOS before the `basemap` release 2.0.0, so that these wheels do not have to rely on manual builds.

**Comment by jameswilburlewis** [comment]
@molinav Yes, that's correct, we would like to support pypi installs on MacOS.   Hopefully with binary wheels supporting ARM, on Ventura and later OS versions.   We don't have an urgent need for Python 3.13 support yet, so if it takes a little longer to get your build workflows working the way you want, we're happy to wait.  I appreciate the effort!

**Comment by cvanelteren** [comment]
hmm strange it seems to build on latest arm for me https://github.com/cvanelteren/basemap/actions/runs/13516075905/job/37764944503

**Comment by cvanelteren** [comment]
@molinav  done!

**Comment by molinav** [comment]
@jameswilburlewis May I ask you to try the wheel below for MacOS ARM64 and Python 3.13? I picked it from one of the last workflows in the `develop` branch. I had to change the extension from `.whl` to `.zip`; otherwise, I could not attach it in my message.

[basemap-2.0.0.dev0-cp313-cp313-macosx_11_0_arm64.zip](https://github.com/user-attachments/files/18972325/basemap-2.0.0.dev0-cp313-cp313-macosx_11_0_arm64.zip)

**Comment by molinav** [comment]
I was checking in PyPI and indeed it is quite unfortunate:
https://pypi.org/project/pyproj/3.7.1/#files

The `pyproj` library is targeting to relatively new MacOS wheel tags for `pyproj` 3.7.1, and it leaves Ventura out for MacOS ARM64:
[pyproj-3.7.1-cp313-cp313-macosx_14_0_arm64.whl](https://files.pythonhosted.org/packages/68/65/6ecdcdc829811a2c160cdfe2f068a009fc572fd4349664f758ccb0853a7c/pyproj-3.7.1-cp313-cp313-macosx_14_0_arm64.whl)
[pyproj-3.7.1-cp313-cp313-macosx_13_0_x86_64.whl](https://files.pythonhosted.org/packages/ef/01/984828464c9960036c602753fc0f21f24f0aa9043c18fa3f2f2b66a86340/pyproj-3.7.1-cp313-cp313-macosx_13_0_x86_64.whl)

If one goes to `pyproj` 3.6.1, when they were supporting only until Python 3.12, the MacOS wheel tags were the typical legacy ones:
[pyproj-3.6.1-cp312-cp312-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/10/f2/b550b1f65cc7e51c9116b220b50aade60c439103432a3fd5b12efbc77e15/pyproj-3.6.1-cp312-cp312-macosx_11_0_arm64.whl)
[pyproj-3.6.1-cp312-cp312-macosx_10_9_x86_64.whl](https://files.pythonhosted.org/packages/0b/64/93232511a7906a492b1b7dfdfc17f4e95982d76a24ef4f86d18cfe7ae2c9/pyproj-3.6.1-cp312-cp312-macosx_10_9_x86_64.whl)

I wonder whether this wheel tag upgrade is really needed by `pyproj` (because of some requirement when building PROJ 9.5.1), or whether it is part of this dropping-support tendency in the Python ecosystem. At least I can say that `basemap` did its part in the migration to Python 3.13!

**Comment by molinav** [comment]
The change in `pyproj` that is moving the MacOS deployment target was introduced in these PRs:
https://github.com/pyproj4/pyproj/pull/1410/files (part of `pyproj` 3.7.0)
https://github.com/pyproj4/pyproj/pull/1475/files (part of `pyproj` 3.7.1)

It looks to me that the `macos_deployment_target` variables are simply updated to match the MacOS version of the host runner. However, I do not see why this is necessary.

**Comment by molinav** [comment]
With PRs #619 and #620, the main problem indicated here is then solved, so I will be closing the issue.

It may still be worth it to report to the `pyproj` developers about this thing with the MacOS deployment target, so that your whole environment continues working in MacOS Ventura.

**Comment by jameswilburlewis** [comment]
@molinav  There are a few other packages that are slow to support MacOs Ventura with Python 3.13 wheels.  I think this is partly due to Github's choice to only offer runners for Sonoma and maybe Sequoia, so projects that do their builds with Github Actions have to go to extra effort to support Ventura.  Thanks very much for your work supporting basemap on this platform!

**Comment by molinav** [comment]
@hidp123 I picked the wheel file from the artifacts generated by the last GitHub workflow at the time (I guess it was [Build #173](https://github.com/matplotlib/basemap/actions/runs/13533679326), but I cannot guarantee it). They are still not available in PyPI though.

**Comment by hidp123** [comment]
Thanks.

Direct link for windows:

https://github.com/matplotlib/basemap/actions/runs/13549514887/artifacts/2657682442
